---
- name: Determine old timezone
  become: true
  shell: "systemsetup -gettimezone | awk -F ': ' '{print $2}'"
  when: macos_timezone.timezone
  register: timezone_old
  changed_when: false

- name: "Set the timezone to {{ macos_timezone.timezone }}; see 'systemsetup -listtimezones' for other values"
  become: true
  command: "systemsetup -settimezone '{{ macos_timezone.timezone }}'"
  when: macos_timezone.timezone and timezone_old.stdout != macos_timezone.timezone

- name: Set macOS defaults
  include_role:
    name: feffi.macos-defaults
  vars:
    macos_defaults:
      defaults:
        - { domain: "NSGlobalDomain", key: "AppleICUForce12HourTime", type: "boolean", value: "{{ not macos_timezone.twentyfour }}", description: "Set 24-Hour time scale" }
        - { domain: "NSGlobalDomain", key: "AppleMeasurementUnits", type: "string", value: "{{ macos_timezone.measurement_units }}", description: "Set the current measurement units" }
        - { domain: "NSGlobalDomain", key: "AppleMetricUnits", type: "boolean", value: "{{ macos_timezone.use_metric_units }}", description: "Set locale to metric units scale" }
        - { domain: "NSGlobalDomain", key: "AppleLocale", type: "string", value: "{{ macos_timezone.locale }}@currency={{ macos_timezone.currency }}", description: "Set the current system locale" }
        - { domain: "NSGlobalDomain", key: "AppleLanguages", type: "array", value: "{{ macos_timezone.languages }}", description: "Set available default languages" }
        - { domain: "NSGlobalDomain", key: "AppleTemperatureUnit", type: "String", value: "{{ macos_timezone.temperature_units }}", description: "Set the current Temperatur unit" }
